### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by suman-somu**
the README hadn't the latest pictures 

updated the latest pictures of the launcher

### CODE REVIEW

**Comment by TBog** [comment]
* The `Homescreen` image is kind of bare. You could make the search bar larger and maybe add a QuickList shortcut or 2
* The `Search 'tbl' ` screen doesn't show any highlights for 'tbl'
* The customize QuickList menu is too empty, maybe select some other page? Like the Actions page.
* The `Customize any icons` screen has invisible shapes, please select a color and set the transparency lower.

**Comment by suman-somu** [comment]
okay , will give you pull request when done .

**Comment by suman-somu** [comment]
updated 

> * The `Homescreen` image is kind of bare. You could make the search bar larger and maybe add a QuickList shortcut or 2 besides the default toggles.
> * The `Search 'tbl'` screen doesn't show any highlights for 'tbl'. You're supposed to show how searching looks like. Feel free to search for something else. I chose tbl because it shows the launcher and also the web search.
> * The customize QuickList menu is too empty, maybe select some other page? Like the Actions page.
> * The `Customize any icons` screen has invisible shapes, please select a color and set the transparency lower.
> 
> You could also use different themes for different screens or you can even show how the same screen looks like with different themes.

**Comment by TBog** [comment]
It much nicer now, thanks.
Just one issue I still have.
The second column header doesn't match the image. Either update the image to highlight `tbl` or update the header to **Search `play`**

**Comment by suman-somu** [comment]
check now , i think it is now all done .

**Comment by suman-somu** [comment]
nice ! 
thanks . i don't know what to say after someone giving me a green square . (laugh ) 

anyways nice working on this .

**Comment by suman-somu** [comment]
and also you should close #202 , as a reminder .

**Pull request merged**
